In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [2]:
FILENAME = '/Users/shanewang/Desktop/Apr.xlsx'
df = pd.read_excel(FILENAME, sheet_name='一级考核-错号率') #一级考核-错号率
raw = df.copy(deep=True)
raw.head()

      行标签  A1题甄别失败  S2题甄别失败  S4a题甄别失败  S4b题甄别失败  S6a题甄别失败  S6题甄别失败  S7题甄别失败      成功  关机/占线/无法接通/语音信箱  过滤问卷拒访   开场白拒访  空号/号码过期  配额已满    时间不宜     停机  未购买此楼盘      未接触  无此人/打错了    无人接听  语言不通  直接挂断/被访者不说话  重复访问  主体问卷拒访  准业主-提前交付（已交付）    接触量  错号数   接通数       错号率
0      集团     15.0     39.0      80.0      46.0      19.0     19.0     34.0  4702.0           2702.0    75.0  1225.0    180.0  31.0  1345.0  101.0    49.0  14683.0     75.0  8348.0  31.0        573.0  30.0   428.0            4.0  20151  444  9101  0.022034
1    上海区域      NaN      8.0       1.0       9.0       8.0      3.0     14.0   722.0            626.0     9.0   219.0     40.0   5.0   161.0   26.0     NaN   2196.0     20.0  1424.0   2.0        114.0   2.0    57.0            1.0   3471   94  1421  0.027082
2    南京公司      NaN      NaN       NaN       NaN       NaN      1.0      NaN    55.0             10.0     NaN    10.0      1.0   NaN     3.0    1.0     NaN     64.0      2.0    43.0   NaN          7.0   NaN     5.0            NaN    138    4    85  0.028986
3  1-准业主1      NaN      NaN       NaN       NaN       NaN      NaN      NaN    12.0              3.0     NaN     3.0      NaN   NaN     1.0    NaN     NaN      4.0      NaN     8.0   NaN          1.0   NaN     1.0            NaN     29    0    18  0.000000
4  2-准业主2      NaN      NaN       NaN       NaN       NaN      NaN      NaN    13.0              1.0     NaN     NaN      NaN   NaN     1.0    NaN     NaN     60.0      NaN     7.0   NaN          1.0   NaN     2.0            NaN     25    0    17  0.000000

In [3]:
def simplify(raw: pd.DataFrame):    
    labels = ['行标签', '总计', '接触量', '接触数','错号数', '错号量']
    for name in raw.columns.tolist():
        if name == '错号数':
            raw.rename(columns={'错号数':'错号量'}, inplace=True)
        if name == '接触数':
            raw.rename(columns={'接触数':'接触量'}, inplace=True)
        if name not in labels:
            raw.drop(name, axis=1, inplace=True)

        
simplify(raw)

raw.head(10)

      行标签    接触量  错号量
0      集团  20151  444
1    上海区域   3471   94
2    南京公司    138    4
3  1-准业主1     29    0
4  2-准业主2     25    0
5  3-磨合期1     80    4
6  4-磨合期2      4    0
7    南通公司     64    1
8  1-准业主1     33    0
9  2-准业主2     31    1

In [4]:
# raw.to_excel('sampleTest.xlsx', index=False)

In [5]:
city_names = []
deprecated_names = ['集团', '上海区域']
# deprecated_names = ['集团']
for name in raw['行标签'].tolist():
    if name not in deprecated_names and '准业主' not in name \
                                    and '磨合期' not in name \
                                    and '老业主' not in name \
                                    and '稳定期' not in name:
        city_names.append(name)

print(city_names)
len(city_names)

['南京公司', '南通公司', '内蒙公司', '浦东公司', '商置公司', '上海公司', '苏北公司', '苏南公司', '苏中公司', '苏州公司', '新疆公司']

11

In [6]:
row_records = []
for _, row in raw.iterrows():
    try:
        row_records.append([row['行标签'], row['接触量'], row['错号量']])
    except Exception as e:
        print(e)
#         row_records.append([row['行标签'], row['总计'], row['错号量']])
    # print(row['行标签'], row['总计'], row['错号数'])
row_records

[['集团', 20151, 444],
 ['上海区域', 3471, 94],
 ['南京公司', 138, 4],
 ['1-准业主1', 29, 0],
 ['2-准业主2', 25, 0],
 ['3-磨合期1', 80, 4],
 ['4-磨合期2', 4, 0],
 ['南通公司', 64, 1],
 ['1-准业主1', 33, 0],
 ['2-准业主2', 31, 1],
 ['内蒙公司', 1, 0],
 ['1-准业主1', 1, 0],
 ['浦东公司', 29, 0],
 ['1-准业主1', 4, 0],
 ['2-准业主2', 22, 0],
 ['3-磨合期1', 3, 0],
 ['商置公司', 2, 0],
 ['1-准业主1', 1, 0],
 ['3-磨合期1', 1, 0],
 ['上海公司', 66, 1],
 ['1-准业主1', 3, 0],
 ['2-准业主2', 48, 1],
 ['4-磨合期2', 15, 0],
 ['苏北公司', 224, 3],
 ['1-准业主1', 53, 1],
 ['2-准业主2', 109, 1],
 ['3-磨合期1', 25, 1],
 ['4-磨合期2', 37, 0],
 ['苏南公司', 2296, 49],
 ['1-准业主1', 198, 5],
 ['2-准业主2', 668, 9],
 ['3-磨合期1', 80, 0],
 ['4-磨合期2', 1350, 35],
 ['苏中公司', 463, 27],
 ['1-准业主1', 72, 9],
 ['2-准业主2', 87, 3],
 ['3-磨合期1', 29, 2],
 ['4-磨合期2', 275, 13],
 ['苏州公司', 167, 9],
 ['1-准业主1', 12, 0],
 ['2-准业主2', 88, 2],
 ['3-磨合期1', 25, 0],
 ['4-磨合期2', 42, 7],
 ['新疆公司', 21, 0],
 ['1-准业主1', 4, 0],
 ['2-准业主2', 17, 0]]

In [7]:
wrong2city = {}
city_appeared = []
cities = []
slice_idx = []
zyz = []
mhq = []
wdq = []
lyz = []

for i in range(0, len(row_records)):
    tag = row_records[i][0]
    if tag in city_names:
        wrong2city[row_records[i][2]] = tag
        city_appeared.append(tag)
        slice_idx.append(i)
slice_idx.append(len(row_records))
for i in range(len(slice_idx)-1):
    cities.append(row_records[slice_idx[i]:slice_idx[i+1]])
print(cities[0])    
print(city_appeared)
print(slice_idx)

[['南京公司', 138, 4], ['1-准业主1', 29, 0], ['2-准业主2', 25, 0], ['3-磨合期1', 80, 4], ['4-磨合期2', 4, 0]]
['南京公司', '南通公司', '内蒙公司', '浦东公司', '商置公司', '上海公司', '苏北公司', '苏南公司', '苏中公司', '苏州公司', '新疆公司']
[2, 7, 10, 12, 16, 19, 23, 28, 33, 38, 43, 46]

In [8]:
for city_info in cities:
    CITY = city_info[0][0]
    for line in city_info[1:]:
        if '准业主' in line[0] and '准业主' != line[0].strip():
            line[0] = CITY + '-' + line[0]
            zyz.append(line)
        if '磨合期' in line[0] and '磨合期' != line[0].strip():
            line[0] = CITY + '-' + line[0]
            mhq.append(line)
        if '稳定期' in line[0] and '稳定期' != line[0].strip():
            line[0] = CITY + '-' + line[0]
            wdq.append(line)
        if '老业主' in line[0] and '老业主' != line[0].strip():
            line[0] = CITY + '-' + line[0]
            lyz.append(line)
zyz

[['南京公司-1-准业主1', 29, 0],
 ['南京公司-2-准业主2', 25, 0],
 ['南通公司-1-准业主1', 33, 0],
 ['南通公司-2-准业主2', 31, 1],
 ['内蒙公司-1-准业主1', 1, 0],
 ['浦东公司-1-准业主1', 4, 0],
 ['浦东公司-2-准业主2', 22, 0],
 ['商置公司-1-准业主1', 1, 0],
 ['上海公司-1-准业主1', 3, 0],
 ['上海公司-2-准业主2', 48, 1],
 ['苏北公司-1-准业主1', 53, 1],
 ['苏北公司-2-准业主2', 109, 1],
 ['苏南公司-1-准业主1', 198, 5],
 ['苏南公司-2-准业主2', 668, 9],
 ['苏中公司-1-准业主1', 72, 9],
 ['苏中公司-2-准业主2', 87, 3],
 ['苏州公司-1-准业主1', 12, 0],
 ['苏州公司-2-准业主2', 88, 2],
 ['新疆公司-1-准业主1', 4, 0],
 ['新疆公司-2-准业主2', 17, 0]]

In [9]:
"""Get city info
    :return format: {CITY: [total, wrong]}
"""
def analyze(l: list):
    res = {}
    for i in range(len(l)):
        city = l[i][0].split('-')[0]
        if not res.__contains__(city):
            res[city] = [l[i][1], l[i][2]]
        else:
            res[city][0] += l[i][1]
            res[city][1] += l[i][2]
    return res

"""Calculate wrong rate
    :return format: {CITY: [total, wrong, wrong rate]}
"""
def calculate(d: dict):
    for k in d.keys():
        print(k, d[k])
        d[k].append(float('{:.5f}'.format(d[k][1]/d[k][0])))
    return d

In [10]:
zyz_list = []
mhq_list = []
wdq_list = []
lyz_list = []
for k, v in calculate(analyze(zyz)).items():
    zyz_list.append(tuple([k, '准业主'] + v))
for k, v in calculate(analyze(mhq)).items():
    mhq_list.append(tuple([k, '磨合期'] + v))
for k, v in calculate(analyze(wdq)).items():
    wdq_list.append(tuple([k, '稳定期'] + v))
for k, v in calculate(analyze(lyz)).items():
    lyz_list.append(tuple([k, '老业主'] + v))

南京公司 [54, 0]
南通公司 [64, 1]
内蒙公司 [1, 0]
浦东公司 [26, 0]
商置公司 [1, 0]
上海公司 [51, 1]
苏北公司 [162, 2]
苏南公司 [866, 14]
苏中公司 [159, 12]
苏州公司 [100, 2]
新疆公司 [21, 0]
南京公司 [84, 4]
浦东公司 [3, 0]
商置公司 [1, 0]
上海公司 [15, 0]
苏北公司 [62, 1]
苏南公司 [1430, 35]
苏中公司 [304, 15]
苏州公司 [67, 7]

In [11]:
labels = ['城市', '业主阶段', '接触量', '错号量', '错号率']
zyz_xlxs = pd.DataFrame(data=zyz_list, columns=labels)
zyz_xlxs = zyz_xlxs.sort_values(by='错号率', ascending=False)
zyz_xlxs.head(20)

      城市 业主阶段  接触量  错号量      错号率
8   苏中公司  准业主  159   12  0.07547
9   苏州公司  准业主  100    2  0.02000
5   上海公司  准业主   51    1  0.01961
7   苏南公司  准业主  866   14  0.01617
1   南通公司  准业主   64    1  0.01562
6   苏北公司  准业主  162    2  0.01235
0   南京公司  准业主   54    0  0.00000
2   内蒙公司  准业主    1    0  0.00000
3   浦东公司  准业主   26    0  0.00000
4   商置公司  准业主    1    0  0.00000
10  新疆公司  准业主   21    0  0.00000

In [12]:
mhq_xlxs = pd.DataFrame(data=mhq_list, columns=labels)
mhq_xlxs = mhq_xlxs.sort_values(by='错号率', ascending=False)
mhq_xlxs.head(20)

     城市 业主阶段   接触量  错号量      错号率
7  苏州公司  磨合期    67    7  0.10448
6  苏中公司  磨合期   304   15  0.04934
0  南京公司  磨合期    84    4  0.04762
5  苏南公司  磨合期  1430   35  0.02448
4  苏北公司  磨合期    62    1  0.01613
1  浦东公司  磨合期     3    0  0.00000
2  商置公司  磨合期     1    0  0.00000
3  上海公司  磨合期    15    0  0.00000

In [13]:
wdq_xlxs = pd.DataFrame(data=wdq_list, columns=labels)
wdq_xlxs = wdq_xlxs.sort_values(by='错号率', ascending=False)
wdq_xlxs.head(20)

Empty DataFrame
Columns: [城市, 业主阶段, 接触量, 错号量, 错号率]
Index: []

In [14]:
lyz_xlxs = pd.DataFrame(data=lyz_list, columns=labels)
lyz_xlxs = lyz_xlxs.sort_values(by='错号率', ascending=False)
lyz_xlxs.head(20)

Empty DataFrame
Columns: [城市, 业主阶段, 接触量, 错号量, 错号率]
Index: []

In [15]:
# Shanghai
def getShanghaiInfo(raw, zyz_xlxs, mhq_xlxs, wdq_xlxs, lyz_xlxs):
    for _, rows in raw.iterrows():
        if '准业主' in rows['行标签']:
            # tuple = ('上海区域', '准业主', rows['接触量'], rows['错号量'], float('{:.5f}'.format(rows['错号量']/rows['接触量'])))
            # print(('上海区域', '准业主', rows['接触量'], rows['错号量'], float('{:.5f}'.format(rows['错号量']/rows['接触量']))))
            shzyz = pd.DataFrame({'城市': ['上海区域'],
                                 '业主阶段': ['准业主'],
                                 '接触量': rows['接触量'],
                                 '错号数': rows['错号量'],
                                 '错号率': float('{:.5f}'.format(rows['错号量']/rows['接触量']))})
            zyz_xlxs = pd.concat([zyz_xlxs, shzyz])

        if '磨合期' in rows['行标签']:
            shmhq = pd.DataFrame({'城市': ['上海区域'],
                                 '业主阶段': ['磨合期'],
                                 '接触量': rows['接触量'],
                                 '错号数': rows['错号量'],
                                 '错号率': float('{:.5f}'.format(rows['错号量']/rows['接触量']))})

            mhq_xlxs = pd.concat([mhq_xlxs, shmhq])
        if '稳定期' in rows['行标签']:
            shwdq = pd.DataFrame({'城市': ['上海区域'],
                                 '业主阶段': ['稳定期'],
                                 '接触量': rows['接触量'],
                                 '错号数': rows['错号量'],
                                 '错号率': float('{:.5f}'.format(rows['错号量']/rows['接触量']))})
            wdq_xlxs = pd.concat([wdq_xlxs, shwdq])
        if '老业主' in rows['行标签']:
            shlyz = pd.DataFrame({'城市': ['上海区域'],
                                 '业主阶段': ['老业主'],
                                 '接触量': rows['接触量'],
                                 '错号数': rows['错号量'],
                                 '错号率': float('{:.5f}'.format(rows['错号量']/rows['接触量']))})
            lyz_xlxs = pd.concat([lyz_xlxs, shlyz])
    return [zyz_xlxs, mhq_xlxs, wdq_xlxs, lyz_xlxs]

dflist = [zyz_xlxs, mhq_xlxs, wdq_xlxs, lyz_xlxs]
try:
    df = pd.read_excel(FILENAME, sheet_name='上海区域')
    raw = df.copy(deep=True)
    simplify(raw)
    dflist = getShanghaiInfo(raw, zyz_xlxs, mhq_xlxs, wdq_xlxs, lyz_xlxs)
except Exception as e:
    print(e)
    # print("No such sheet!")
    pass

No sheet named <'上海区域'>

In [16]:
# funtion
def multiple_dfs(df_list, sheets, file_name, spaces):
    writer = pd.ExcelWriter(file_name,engine='xlsxwriter')   
    row = 0
    for dataframe in df_list:
        dataframe.to_excel(writer,sheet_name=sheets,startrow=row , startcol=0, index=False)   
        row = row + len(dataframe.index) + spaces + 1
    writer.save()

# write list of dataframes
multiple_dfs(dflist, 'Validation', 'Apr-20200430.xlsx', 1)